from typing import List, Dict
from app.models.schemas import (
    SERPSnapshot,
    SERPItem,
    OptimizationAction,
    ActionCategory,
    CompetitorDiff,
    MemoryNode,
    AttributionVerdict,
    RecommendationItem,
    EvidenceTier,
    AuditReport,
)

SEED_QUERY = "best python courses for beginners"
SEED_TARGET_DOMAIN = "learnpythonhub.io"

# Snapshot 0: 90 Days Ago (Baseline)
SNAPSHOT_0 = SERPSnapshot(
    id="snap_000_baseline",
    query=SEED_QUERY,
    timestamp="2026-06-15T10:00:00Z",
    cycle_index=0,
    total_results_evaluated=10,
    items=[
        SERPItem(
            rank=1,
            url="https://www.coursera.org/specializations/python",
            domain="coursera.org",
            title="Python for Everybody Specialization | Coursera",
            snippet="Learn to Program and Analyze Data with Python. Develop programs to clean, analyze, and visualize data.",
            word_count=3400,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=True,
            schema_types=["Course", "Organization"],
            last_updated="2026-05-20",
            readability_score=82.0,
            citation_density=4.1,
            intent_match_score=95.0,
        ),
        SERPItem(
            rank=2,
            url="https://www.codecademy.com/learn/learn-python-3",
            domain="codecademy.com",
            title="Learn Python 3 | Codecademy",
            snippet="Learn Python 3 with our interactive, hands-on course. Build real-world projects and earn a certificate.",
            word_count=2200,
            has_interactive_widget=True,
            has_video_preview=False,
            has_curriculum_table=True,
            schema_types=["Course", "FAQPage"],
            last_updated="2026-06-01",
            readability_score=85.0,
            citation_density=3.2,
            intent_match_score=94.0,
        ),
        SERPItem(
            rank=3,
            url="https://www.freecodecamp.org/news/python-for-beginners-full-course/",
            domain="freecodecamp.org",
            title="Python for Beginners - Full Course | freeCodeCamp.org",
            snippet="This complete Python course will take you from zero programming experience to confident fundamentals.",
            word_count=4800,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=False,
            schema_types=["Article", "VideoObject"],
            last_updated="2026-04-10",
            readability_score=78.0,
            citation_density=5.0,
            intent_match_score=91.0,
        ),
        SERPItem(
            rank=4,
            url="https://www.udemy.com/course/complete-python-bootcamp/",
            domain="udemy.com",
            title="2026 Complete Python Bootcamp From Zero to Hero | Udemy",
            snippet="Learn Python like a Professional! Start from the basics and go all the way to creating your own applications.",
            word_count=2900,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=True,
            schema_types=["Course", "AggregateRating"],
            last_updated="2026-06-10",
            readability_score=80.0,
            citation_density=2.8,
            intent_match_score=89.0,
        ),
        SERPItem(
            rank=5,
            url="https://realpython.com/learning-paths/python-basics/",
            domain="realpython.com",
            title="Python Basics: A Practical Introduction | Real Python",
            snippet="Learn Python step by step with clear explanations, code samples, and guided learning tracks.",
            word_count=4100,
            has_interactive_widget=False,
            has_video_preview=False,
            has_curriculum_table=True,
            schema_types=["Article", "BreadcrumbList"],
            last_updated="2026-05-18",
            readability_score=84.0,
            citation_density=6.2,
            intent_match_score=88.0,
        ),
        SERPItem(
            rank=6,
            url="https://www.edx.org/course/introduction-to-computer-science-and-programming-using-python",
            domain="edx.org",
            title="CS50: Introduction to Computer Science & Python | edX",
            snippet="An introduction to computer science and programming using Python from Harvard and MIT faculty.",
            word_count=2600,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=True,
            schema_types=["Course"],
            last_updated="2026-05-01",
            readability_score=76.0,
            citation_density=4.5,
            intent_match_score=87.0,
        ),
        SERPItem(
            rank=7,
            url="https://www.pluralsight.com/courses/core-python-getting-started",
            domain="pluralsight.com",
            title="Core Python: Getting Started | Pluralsight",
            snippet="Learn core Python syntax, libraries, and tooling designed for software engineers and aspiring data analysts.",
            word_count=2100,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=False,
            schema_types=["Course"],
            last_updated="2026-03-12",
            readability_score=79.0,
            citation_density=2.1,
            intent_match_score=84.0,
        ),
        SERPItem(
            rank=8,
            url="https://learnpythonhub.io/best-python-courses-beginners",
            domain="learnpythonhub.io",
            title="Best Python Courses for Beginners in 2026 (Curated Guide)",
            snippet="Our comprehensive comparison of the top Python courses for absolute beginners, evaluated on cost and depth.",
            word_count=2400,
            has_interactive_widget=False,
            has_video_preview=False,
            has_curriculum_table=False,
            schema_types=["Article"],
            last_updated="2026-04-02",
            readability_score=76.0,
            citation_density=3.0,
            intent_match_score=82.0,
        ),
    ],
)

# Action 1: 75 Days Ago - User attempted generic word count expansion
ACTION_1 = OptimizationAction(
    id="act_001_word_count_fluff",
    query=SEED_QUERY,
    target_domain=SEED_TARGET_DOMAIN,
    target_url="https://learnpythonhub.io/best-python-courses-beginners",
    timestamp="2026-07-01T14:30:00Z",
    category=ActionCategory.CONTENT_DEPTH,
    title="Expanded Article Length (+1,600 words)",
    description="Added 1,600 words of generic descriptive text covering Python history, installation notes, and broad overview paragraphs.",
    hypothesis="Competitors have high word counts (3,000+ words). Increasing length should signal higher comprehensiveness to Google.",
    snapshot_before_id="snap_000_baseline",
)

# Snapshot 1: 60 Days Ago - Post-Action 1 Evaluation
SNAPSHOT_1 = SERPSnapshot(
    id="snap_001_post_fluff",
    query=SEED_QUERY,
    timestamp="2026-07-20T10:00:00Z",
    cycle_index=1,
    total_results_evaluated=10,
    items=[
        item.model_copy() for item in SNAPSHOT_0.items
    ],
)
# Update our target item in snapshot 1 (word count increased to 4000, rank remained unchanged at #8)
for item in SNAPSHOT_1.items:
    if item.domain == SEED_TARGET_DOMAIN:
        item.word_count = 4000
        item.rank = 8
        item.last_updated = "2026-07-01"

# Memory Node 1: Learned lesson from Action 1
MEMORY_NODE_1 = MemoryNode(
    id="mem_001_word_count_ineffective",
    query=SEED_QUERY,
    target_domain=SEED_TARGET_DOMAIN,
    action_id="act_001_word_count_fluff",
    action_category=ActionCategory.CONTENT_DEPTH,
    action_title="Expanded Article Length (+1,600 words)",
    date_applied="2026-07-01",
    date_evaluated="2026-07-20",
    latency_days=19,
    rank_before=8,
    rank_after=8,
    rank_delta=0,
    verdict=AttributionVerdict.NEUTRAL,
    confidence_score=0.92,
    agent_distilled_lesson="Increasing passive word count without structured data or interactive utility produced zero ranking movement in this intent cluster. Beginners search for actionable evaluation, not encyclopedia text.",
)

# Action 2: 45 Days Ago - User pivoted to Interactive UX & Curriculum Comparison Matrix
ACTION_2 = OptimizationAction(
    id="act_002_interactive_matrix",
    query=SEED_QUERY,
    target_domain=SEED_TARGET_DOMAIN,
    target_url="https://learnpythonhub.io/best-python-courses-beginners",
    timestamp="2026-08-05T09:15:00Z",
    category=ActionCategory.INTERACTIVE_UX,
    title="Embedded In-Browser Code Runner & Course Comparison Matrix",
    description="Replaced generic text blocks with an interactive Python mini-sandbox widget (run your first 'print' statement) and an interactive filterable matrix comparing price, duration, and project count.",
    hypothesis="Beginner learners reward immediate tactile engagement; interactive tools match Codecademy's user engagement dwell signals.",
    snapshot_before_id="snap_001_post_fluff",
)

# Snapshot 2: 30 Days Ago - Post-Action 2 (Rank jumped from #8 to #3!)
SNAPSHOT_2 = SERPSnapshot(
    id="snap_002_post_interactive",
    query=SEED_QUERY,
    timestamp="2026-08-28T10:00:00Z",
    cycle_index=2,
    total_results_evaluated=10,
    items=[
        SERPItem(
            rank=1,
            url="https://www.coursera.org/specializations/python",
            domain="coursera.org",
            title="Python for Everybody Specialization | Coursera",
            snippet="Learn to Program and Analyze Data with Python. Develop programs to clean, analyze, and visualize data.",
            word_count=3450,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=True,
            schema_types=["Course", "Organization"],
            last_updated="2026-05-20",
            readability_score=82.0,
            citation_density=4.1,
            intent_match_score=95.0,
        ),
        SERPItem(
            rank=2,
            url="https://www.codecademy.com/learn/learn-python-3",
            domain="codecademy.com",
            title="Learn Python 3 | Codecademy",
            snippet="Learn Python 3 with our interactive, hands-on course. Build real-world projects and earn a certificate.",
            word_count=2250,
            has_interactive_widget=True,
            has_video_preview=False,
            has_curriculum_table=True,
            schema_types=["Course", "FAQPage"],
            last_updated="2026-07-15",
            readability_score=86.0,
            citation_density=3.4,
            intent_match_score=94.0,
        ),
        SERPItem(
            rank=3,
            url="https://learnpythonhub.io/best-python-courses-beginners",
            domain="learnpythonhub.io",
            title="Best Python Courses for Beginners (Interactive Comparison & Sandbox)",
            snippet="Compare the top Python courses with our live sandbox demo and interactive curriculum matrix.",
            word_count=3600,
            has_interactive_widget=True,
            has_video_preview=False,
            has_curriculum_table=True,
            schema_types=["Article", "ItemList"],
            last_updated="2026-08-05",
            readability_score=83.0,
            citation_density=4.5,
            intent_match_score=93.0,
        ),
        SERPItem(
            rank=4,
            url="https://www.freecodecamp.org/news/python-for-beginners-full-course/",
            domain="freecodecamp.org",
            title="Python for Beginners - Full Course | freeCodeCamp.org",
            snippet="This complete Python course will take you from zero programming experience to confident fundamentals.",
            word_count=4800,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=False,
            schema_types=["Article", "VideoObject"],
            last_updated="2026-04-10",
            readability_score=78.0,
            citation_density=5.0,
            intent_match_score=90.0,
        ),
        SERPItem(
            rank=5,
            url="https://www.udemy.com/course/complete-python-bootcamp/",
            domain="udemy.com",
            title="2026 Complete Python Bootcamp From Zero to Hero | Udemy",
            snippet="Learn Python like a Professional! Start from the basics and go all the way to creating your own applications.",
            word_count=2950,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=True,
            schema_types=["Course", "AggregateRating"],
            last_updated="2026-08-01",
            readability_score=80.0,
            citation_density=2.8,
            intent_match_score=88.0,
        ),
    ],
)

# Memory Node 2: Positive attribution from Action 2
MEMORY_NODE_2 = MemoryNode(
    id="mem_002_interactive_success",
    query=SEED_QUERY,
    target_domain=SEED_TARGET_DOMAIN,
    action_id="act_002_interactive_matrix",
    action_category=ActionCategory.INTERACTIVE_UX,
    action_title="Embedded In-Browser Code Runner & Course Comparison Matrix",
    date_applied="2026-08-05",
    date_evaluated="2026-08-28",
    latency_days=23,
    rank_before=8,
    rank_after=3,
    rank_delta=5,
    verdict=AttributionVerdict.CONFIRMED_POSITIVE,
    confidence_score=0.95,
    agent_distilled_lesson="Adding an interactive code widget and structured curriculum comparison table triggered a massive +5 rank surge (#8 → #3). Tactile engagement and scannable tabular structure strongly aligned with beginner query intent.",
)

# Competitor Counter-Attack: 15 Days Ago
COMPETITOR_DIFF_1 = CompetitorDiff(
    id="diff_001_coursera_counter",
    query=SEED_QUERY,
    domain="coursera.org",
    cycle_from=2,
    cycle_to=3,
    rank_delta=0,
    changes_detected=[
        "Added interactive project preview modules",
        "Added CourseSchema rich snippet with accredited certificates",
        "Updated H2 headers targeting 'Python courses with certificates for beginners'",
    ],
    feature_shifts={"has_interactive_widget": True, "has_video_preview": True},
)

# Snapshot 3: Current Snapshot (Today)
SNAPSHOT_3_CURRENT = SERPSnapshot(
    id="snap_003_current",
    query=SEED_QUERY,
    timestamp="2026-09-27T22:00:00Z",
    cycle_index=3,
    total_results_evaluated=10,
    items=[
        SERPItem(
            rank=1,
            url="https://www.coursera.org/specializations/python",
            domain="coursera.org",
            title="Python for Everybody Specialization | Coursera",
            snippet="Learn to Program and Analyze Data with Python. Interactive practice projects and accredited university certificates.",
            word_count=3600,
            has_interactive_widget=True,
            has_video_preview=True,
            has_curriculum_table=True,
            schema_types=["Course", "Organization", "EducationalOccupationalCredential"],
            last_updated="2026-09-12",
            readability_score=84.0,
            citation_density=4.3,
            intent_match_score=97.0,
        ),
        SERPItem(
            rank=2,
            url="https://www.codecademy.com/learn/learn-python-3",
            domain="codecademy.com",
            title="Learn Python 3 | Codecademy",
            snippet="Learn Python 3 with our interactive, hands-on course. Build real-world projects and earn a certificate.",
            word_count=2300,
            has_interactive_widget=True,
            has_video_preview=False,
            has_curriculum_table=True,
            schema_types=["Course", "FAQPage"],
            last_updated="2026-09-01",
            readability_score=86.0,
            citation_density=3.4,
            intent_match_score=94.0,
        ),
        SERPItem(
            rank=3,
            url="https://www.freecodecamp.org/news/python-for-beginners-full-course/",
            domain="freecodecamp.org",
            title="Python for Beginners - Full Course (Video & Certificate) | freeCodeCamp.org",
            snippet="Complete Python beginner video curriculum with interactive chapter markers and verified free certificate.",
            word_count=4900,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=True,
            schema_types=["Article", "VideoObject", "Course"],
            last_updated="2026-09-15",
            readability_score=81.0,
            citation_density=5.2,
            intent_match_score=93.0,
        ),
        SERPItem(
            rank=4,
            url="https://learnpythonhub.io/best-python-courses-beginners",
            domain="learnpythonhub.io",
            title="Best Python Courses for Beginners (Interactive Comparison & Sandbox)",
            snippet="Compare the top Python courses with our live sandbox demo and interactive curriculum matrix.",
            word_count=3650,
            has_interactive_widget=True,
            has_video_preview=False,
            has_curriculum_table=True,
            schema_types=["Article", "ItemList"],
            last_updated="2026-08-05",
            readability_score=83.0,
            citation_density=4.5,
            intent_match_score=91.0,
        ),
        SERPItem(
            rank=5,
            url="https://www.udemy.com/course/complete-python-bootcamp/",
            domain="udemy.com",
            title="2026 Complete Python Bootcamp From Zero to Hero | Udemy",
            snippet="Learn Python like a Professional! Start from the basics and go all the way to creating your own applications.",
            word_count=2950,
            has_interactive_widget=False,
            has_video_preview=True,
            has_curriculum_table=True,
            schema_types=["Course", "AggregateRating"],
            last_updated="2026-08-01",
            readability_score=80.0,
            citation_density=2.8,
            intent_match_score=88.0,
        ),
    ],
)

# Current Recommendations Synthesized by RankMind Strategy Agent
SEED_RECOMMENDATIONS = [
    RecommendationItem(
        id="rec_001_video_walkthroughs",
        title="Embed Video Project Walkthroughs & VideoObject Schema",
        category=ActionCategory.MULTIMEDIA_EXPANSION,
        evidence_tier=EvidenceTier.COMPETITOR_TREND,
        rationale="All top 3 competitors (Coursera #1, freeCodeCamp #3) feature video walkthrough previews with structured timestamps. Our page currently lacks video content.",
        expected_impact="+1 to +2 positions (re-overtaking freeCodeCamp #3)",
        historical_precedent="freeCodeCamp leapfrogged our #3 spot (+1) after refreshing video timestamps in September.",
        priority=1,
    ),
    RecommendationItem(
        id="rec_002_certificate_schema",
        title="Implement Course & Credential Schema Markup",
        category=ActionCategory.SCHEMA_MARKUP,
        evidence_tier=EvidenceTier.HISTORICALLY_PROVEN,
        rationale="Our page currently only uses generic Article & ItemList schema. Coursera and freeCodeCamp dominate the top SERP rich snippet carousel using Course and EducationalOccupationalCredential schemas.",
        expected_impact="Rich snippet carousel eligibility, higher SERP CTR",
        historical_precedent="Structured data adoption in Cycle 2 correlated with initial snippet capture.",
        priority=2,
    ),
    RecommendationItem(
        id="rec_003_freshness_update",
        title="Execute Q4 Freshness Update & Price Verification",
        category=ActionCategory.FRESHNESS_UPDATE,
        evidence_tier=EvidenceTier.HISTORICALLY_PROVEN,
        rationale="Our last update timestamp is August 5th (53 days stale). Top 3 competitors all updated within the last 15–25 days.",
        expected_impact="Protects against algorithm freshness decay",
        historical_precedent="Competitor freshness updates in Cycle 3 triggered recent rank slip from #3 to #4.",
        priority=3,
    ),
]
